### ISSUE TITLE
Is this still faster than calling `writeAndFlush()` ?

### ISSUE THREAD

**Issue by LoneDev6** [stepancheg/netty-td#1]
Hello!
Thanks a lot for your library, but is this still faster than `writeAndFlush()` for high frequency sent packets? Is it still needed on the very latest netty builds?
Thanks!

**Comment by stepancheg** [comment]
It was ten years ago, I don't really know what's going on with netty these days, sorry.

**Comment by LoneDev6** [comment]
No problem!
Thanks for your time
